### ISSUE TITLE
Error when generate with "types" option

### ISSUE THREAD

**Issue by Romaixn** [pmndrs/gltf-react-three#29]
Hi ! Thanks for this awesome tool !

I have an error when generated components with "types" option (on all my models)  using `.tsx` files : 
```
Conversion of type 'GLTF & ObjectMap' to type 'GLTFResult' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  Type 'GLTF & ObjectMap' is not comparable to type '{ nodes: { Mesh_wave_C: Mesh<BufferGeometry, Material | Material[]>; Mesh_wave_C_1: Mesh<BufferGeometry, Material | Material[]>; }; materials: { ...; }; }'.
    Types of property 'nodes' are incompatible.
      Type '{ [name: string]: Object3D<Event>; }' is missing the following properties from type '{ Mesh_wave_C: Mesh<BufferGeometry, Material | Material[]>; Mesh_wave_C_1: Mesh<BufferGeometry, Material | Material[]>; }': Mesh_wave_C, Mesh_wave_C_1
```

Is moving from this: ` const { nodes, materials } = useGLTF("/models/tree.glb") as GLTFResult;`
to this: `  const { nodes, materials } = useGLTF("/models/tree.glb") as unknown as GLTFResult;` a good solution?

Thanks 🙏🏻

**Comment by SaraVieira** [comment]
Hey!

This seems like an issue on react three fiber core more than in here and i also unfortunately do not have enough TS knowledge

Please make an issue here https://github.com/pmndrs/react-three-fiber, you may get more luck

**Comment by ChrisCoastal** [comment]
@SaraVieira @Romaixn I was running into the same typing issue and eventually found that, in my case, deconstructing `{ nodes, materials }` and the auto-generated code was the source of glitchy renders in my app. Not sure if this is due to a change with drei or not, but I was able to fix both problems by passing the scene to React Three Fiber's `<primative />`

```
export function Model(props) {
  const { nodes, materials } = useGLTF("/myscene.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Plane.geometry}
        material={nodes.Plane.material}
      />
     // etc.
    </group>
  );
```

fixes typing issue and render glitch
```
import { Canvas } from '@react-three/fiber';

export function Model(props) {
  const gtlf = useGLTF("/myscene.gltf");
  return (
    <Canvas>
      // this now renders correctly
      <primitive object={gltf.scene} />
   </Canvas>
  );
```

Not sure how to approach a fix for this as it looks like [the code is parsed from `gltfjsx` here](https://github.com/pmndrs/gltf-react-three/blob/3ebb0aa446725a5ec375b3b9d301670a10e7fb70/utils/store.js#L44), but it is causing more than just a typing issue.

**Comment by SaraVieira** [comment]
Going to close to keep this cleaner
